USE BD_ACTIVOS;
GO

CREATE TABLE CATEGORIAS
(
    ID_CAT INT IDENTITY(1,1) PRIMARY KEY,
    NOM_CAT NVARCHAR(100) NOT NULL,
    VID_UTI_ANIOS INT NOT NULL,
    POR_VAL_RES DECIMAL(5,2) NOT NULL,

    CONSTRAINT CK_CATEGORIAS_VIDA
        CHECK (VID_UTI_ANIOS > 0),

    CONSTRAINT CK_CATEGORIAS_RESIDUAL
        CHECK (POR_VAL_RES >= 0 AND POR_VAL_RES <= 100)
);
GO

INSERT INTO CATEGORIAS
    (NOM_CAT, VID_UTI_ANIOS, POR_VAL_RES)
VALUES
    ('Edificios e inmuebles', 20, 10),
    ('Tecnologías', 3, 10),
    ('Vehículos', 5, 10);
GO

CREATE TABLE TIPOS_ACTIVOS
(
    ID_TIPO INT IDENTITY(1,1) PRIMARY KEY,
    NOM_TIPO NVARCHAR(100) NOT NULL,
    ID_CAT_PER INT NOT NULL,

    CONSTRAINT FK_TIPOS_CATEGORIAS
        FOREIGN KEY (ID_CAT_PER)
        REFERENCES CATEGORIAS(ID_CAT)
);
GO

INSERT INTO TIPOS_ACTIVOS
    (NOM_TIPO, ID_CAT_PER)
VALUES
    ('Computadora', 2),
    ('Laptop', 2),
    ('Impresora', 2),
    ('Monitor', 2),
    ('Servidor', 2),
    ('Proyector', 2),
    ('Moto', 3),
    ('Camioneta', 3),
    ('Automóvil', 3),
    ('Edificio', 1),
    ('Oficina', 1),
    ('Bodega', 1);
GO

CREATE TABLE ACTIVOS
(
    ID_ACT INT IDENTITY(1,1) PRIMARY KEY,
    DES_ACT NVARCHAR(200) NOT NULL,
    ID_TIP_PER INT NOT NULL,
    FECHA_COMPRA DATE NOT NULL,
    VALOR_COMPRA DECIMAL(12,2) NOT NULL,
    ID_USU_PER INT NOT NULL,

    CONSTRAINT FK_ACTIVOS_TIPOS
        FOREIGN KEY (ID_TIP_PER)
        REFERENCES TIPOS_ACTIVOS(ID_TIPO),

    CONSTRAINT CK_ACTIVOS_VALOR
        CHECK (VALOR_COMPRA > 0)
);
GO