USE BD_AUTH;
GO

CREATE TABLE USUARIOS
(
    ID_USU INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    APELLIDO NVARCHAR(100) NOT NULL,
    CORREO NVARCHAR(150) NOT NULL UNIQUE,
    NOMBRE_USUARIO NVARCHAR(50) NOT NULL UNIQUE,
    PASSWORD_HASH NVARCHAR(255) NOT NULL,
    ESTADO NVARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    FECHA_REGISTRO DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

    CONSTRAINT CK_USUARIOS_ESTADO
        CHECK (ESTADO IN ('ACTIVO', 'INACTIVO'))
);
GO

CREATE TABLE VERIFICACIONES
(
    ID_VER INT IDENTITY(1,1) PRIMARY KEY,
    ID_USU INT NOT NULL,
    CODIGO NVARCHAR(6) NOT NULL,
    EXPIRA DATETIME2 NOT NULL,
    USADO BIT NOT NULL DEFAULT 0,
    FECHA_CREACION DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

    CONSTRAINT FK_VERIFICACIONES_USUARIOS
        FOREIGN KEY (ID_USU)
        REFERENCES USUARIOS(ID_USU)
);
GO