USE BD_DEPRECIACION;
GO

CREATE TABLE DETALLE_DEPRECIACION
(
    ID_ACTIVO INT NOT NULL,
    ANIO_DEP INT NOT NULL,
    FECHA_CORTE DATE NOT NULL,
    MESES_DEPRECIADOS INT NOT NULL,
    VALOR_INICIAL DECIMAL(12,2) NOT NULL,
    DEPRECIACION_PERIODO DECIMAL(12,2) NOT NULL,
    DEPRECIACION_ACUMULADA DECIMAL(12,2) NOT NULL,
    VALOR_ACTUAL DECIMAL(12,2) NOT NULL,

    CONSTRAINT PK_DETALLE_DEPRECIACION
        PRIMARY KEY (ID_ACTIVO, ANIO_DEP),

    CONSTRAINT CK_DETALLE_ANIO
        CHECK (ANIO_DEP > 0),

    CONSTRAINT CK_DETALLE_MESES
        CHECK (MESES_DEPRECIADOS >= 0),

    CONSTRAINT CK_DETALLE_VALORES
        CHECK (
            VALOR_INICIAL >= 0 AND
            DEPRECIACION_PERIODO >= 0 AND
            DEPRECIACION_ACUMULADA >= 0 AND
            VALOR_ACTUAL >= 0
        )
);
GO